package musicbrainz

import "strings"

// CodeToCountry maps ISO 3166-1 alpha-2 country codes to the full
// country names used elsewhere in Fisher (e.g. geo_expand's
// DefaultGeoCountries). This keeps genres.countries consistent
// regardless of whether the data came from MusicBrainz (ISO codes)
// or Last.fm geo expansion (full names).
var CodeToCountry = map[string]string{
	"AF": "Afghanistan",
	"AL": "Albania",
	"DZ": "Algeria",
	"AR": "Argentina",
	"AU": "Australia",
	"AT": "Austria",
	"BD": "Bangladesh",
	"BY": "Belarus",
	"BE": "Belgium",
	"BO": "Bolivia",
	"BA": "Bosnia and Herzegovina",
	"BR": "Brazil",
	"BG": "Bulgaria",
	"KH": "Cambodia",
	"CM": "Cameroon",
	"CA": "Canada",
	"CL": "Chile",
	"CN": "China",
	"CO": "Colombia",
	"CR": "Costa Rica",
	"HR": "Croatia",
	"CU": "Cuba",
	"CZ": "Czech Republic",
	"DK": "Denmark",
	"DO": "Dominican Republic",
	"EC": "Ecuador",
	"EG": "Egypt",
	"EE": "Estonia",
	"FI": "Finland",
	"FR": "France",
	"DE": "Germany",
	"GH": "Ghana",
	"GR": "Greece",
	"GT": "Guatemala",
	"HT": "Haiti",
	"HN": "Honduras",
	"HK": "Hong Kong",
	"HU": "Hungary",
	"IS": "Iceland",
	"IN": "India",
	"ID": "Indonesia",
	"IR": "Iran",
	"IQ": "Iraq",
	"IE": "Ireland",
	"IL": "Israel",
	"IT": "Italy",
	"JM": "Jamaica",
	"JP": "Japan",
	"JO": "Jordan",
	"KZ": "Kazakhstan",
	"KE": "Kenya",
	"KR": "South Korea",
	"KW": "Kuwait",
	"KG": "Kyrgyzstan",
	"LA": "Laos",
	"LV": "Latvia",
	"LB": "Lebanon",
	"LT": "Lithuania",
	"MO": "Macao",
	"MK": "North Macedonia",
	"MG": "Madagascar",
	"MY": "Malaysia",
	"ML": "Mali",
	"MT": "Malta",
	"MU": "Mauritius",
	"MX": "Mexico",
	"MD": "Moldova",
	"MN": "Mongolia",
	"MA": "Morocco",
	"MZ": "Mozambique",
	"MM": "Myanmar",
	"NA": "Namibia",
	"NP": "Nepal",
	"NL": "Netherlands",
	"NZ": "New Zealand",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"NO": "Norway",
	"OM": "Oman",
	"PK": "Pakistan",
	"PS": "Palestine",
	"PA": "Panama",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Philippines",
	"PL": "Poland",
	"PT": "Portugal",
	"QA": "Qatar",
	"RO": "Romania",
	"RU": "Russia",
	"SA": "Saudi Arabia",
	"SN": "Senegal",
	"RS": "Serbia",
	"SG": "Singapore",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"ZA": "South Africa",
	"ES": "Spain",
	"LK": "Sri Lanka",
	"SD": "Sudan",
	"SE": "Sweden",
	"CH": "Switzerland",
	"SY": "Syria",
	"TW": "Taiwan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TN": "Tunisia",
	"TR": "Turkey",
	"UG": "Uganda",
	"UA": "Ukraine",
	"AE": "United Arab Emirates",
	"GB": "United Kingdom",
	"US": "United States",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"YE": "Yemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
}

// NormalizeCountry converts an ISO 3166-1 alpha-2 code to its full
// country name. If the input is already a full name (or unknown), it
// is returned as-is.
func NormalizeCountry(codeOrName string) string {
	if full, ok := CodeToCountry[strings.ToUpper(codeOrName)]; ok {
		return full
	}
	return codeOrName
}
